param(
  [switch]$SkipStartupTasks
)

$ErrorActionPreference = "Stop"

function Write-Step([string]$Message) {
  Write-Host ""
  Write-Host "==> $Message" -ForegroundColor Cyan
}

if ($env:OS -ne "Windows_NT") {
  throw "This installer is for Windows only."
}

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$RepoRoot = (Resolve-Path (Join-Path $ScriptDir "..\..")).Path
$BinDir = Join-Path $ScriptDir "bin"
$ToolsDir = Join-Path $ScriptDir "tools"
$VenvPython = Join-Path $RepoRoot ".venv\Scripts\python.exe"
$PipExe = Join-Path $RepoRoot ".venv\Scripts\pip.exe"

$Go2rtcVersion = "1.9.13"
$CaddyVersion = "2.8.4"
$CloudflaredVersion = "2026.3.0"

New-Item -ItemType Directory -Force -Path $BinDir | Out-Null
New-Item -ItemType Directory -Force -Path $ToolsDir | Out-Null

function Download-File {
  param(
    [Parameter(Mandatory = $true)][string]$Url,
    [Parameter(Mandatory = $true)][string]$OutFile
  )
  Write-Host "Downloading $Url"
  Invoke-WebRequest -Uri $Url -OutFile $OutFile
}

function Ensure-Python {
  Write-Step "Checking Python"
  try {
    & py -3 --version | Out-Null
  } catch {
    throw "Python 3 not found. Install Python 3.10+ and rerun."
  }
}

function Setup-Venv {
  Write-Step "Creating virtual environment"
  if (!(Test-Path $VenvPython)) {
    Push-Location $RepoRoot
    & py -3 -m venv .venv
    Pop-Location
  }

  Write-Step "Installing Python dependencies"
  & $PipExe install --upgrade pip
  & $PipExe install -r (Join-Path $RepoRoot "requirements.txt")
}

function Install-Go2rtc {
  Write-Step "Installing go2rtc"
  $zipPath = Join-Path $ToolsDir "go2rtc_windows_amd64.zip"
  $url = "https://github.com/AlexxIT/go2rtc/releases/download/v$Go2rtcVersion/go2rtc_windows_amd64.zip"
  Download-File -Url $url -OutFile $zipPath

  $extractPath = Join-Path $ToolsDir "go2rtc_extract"
  if (Test-Path $extractPath) { Remove-Item -Recurse -Force $extractPath }
  Expand-Archive -Path $zipPath -DestinationPath $extractPath -Force
  Copy-Item (Join-Path $extractPath "go2rtc.exe") (Join-Path $BinDir "go2rtc.exe") -Force
}

function Install-Caddy {
  Write-Step "Installing Caddy"
  $zipPath = Join-Path $ToolsDir "caddy_windows_amd64.zip"
  $url = "https://github.com/caddyserver/caddy/releases/download/v$CaddyVersion/caddy_$CaddyVersion`_windows_amd64.zip"
  Download-File -Url $url -OutFile $zipPath

  $extractPath = Join-Path $ToolsDir "caddy_extract"
  if (Test-Path $extractPath) { Remove-Item -Recurse -Force $extractPath }
  Expand-Archive -Path $zipPath -DestinationPath $extractPath -Force
  Copy-Item (Join-Path $extractPath "caddy.exe") (Join-Path $BinDir "caddy.exe") -Force
}

function Install-Cloudflared {
  Write-Step "Installing Cloudflared"
  $exePath = Join-Path $BinDir "cloudflared.exe"
  $url = "https://github.com/cloudflare/cloudflared/releases/download/$CloudflaredVersion/cloudflared-windows-amd64.exe"
  Download-File -Url $url -OutFile $exePath
}

function Update-Config {
  Write-Step "Applying production-friendly defaults to config.ini"
  $cfgPath = Join-Path $RepoRoot "config.ini"
  $bootstrapPath = Join-Path $ScriptDir "bootstrap-admin.txt"
  $code = @"
import configparser, pathlib, secrets
cfg_path = pathlib.Path(r"$cfgPath")
bootstrap_path = pathlib.Path(r"$bootstrapPath")
cfg = configparser.ConfigParser()
cfg.read(cfg_path)
if not cfg.has_section("web"):
    cfg.add_section("web")
if cfg.get("web", "secret_key", fallback="change-this-to-a-random-secret-key") == "change-this-to-a-random-secret-key":
    cfg.set("web", "secret_key", secrets.token_hex(32))
cfg.set("web", "host", "127.0.0.1")
cfg.set("web", "port", "5001")
generated_password = ""
default_pass = cfg.get("web", "dashboard_password", fallback="admin123")
if default_pass == "admin123":
    generated_password = secrets.token_urlsafe(12)
    cfg.set("web", "dashboard_username", "admin")
    cfg.set("web", "dashboard_password", generated_password)
if not cfg.has_section("go2rtc"):
    cfg.add_section("go2rtc")
cfg.set("go2rtc", "enabled", "true")
cfg.set("go2rtc", "base_url", "http://127.0.0.1:1984")
cfg.set("go2rtc", "proxy_path", "/go2rtc")
if not cfg.has_section("setup"):
    cfg.add_section("setup")
if cfg.get("setup", "completed", fallback="false").lower() != "true":
    cfg.set("setup", "completed", "false")
with cfg_path.open("w") as f:
    cfg.write(f)
bootstrap_lines = [
    "CamMonitor bootstrap credentials",
    f"Username: {cfg.get('web', 'dashboard_username')}",
]
if generated_password:
    bootstrap_lines.append(f"Password: {generated_password}")
    bootstrap_lines.append("Status: Generated by installer (default password replaced).")
else:
    bootstrap_lines.append("Password: unchanged from existing config")
    bootstrap_lines.append("Status: Existing admin password preserved.")
bootstrap_path.write_text("\n".join(bootstrap_lines) + "\n", encoding="utf-8")
print(f"Bootstrap credentials saved to: {bootstrap_path}")
"@
  & $VenvPython -c $code
}

function Ensure-CloudflaredTemplate {
  Write-Step "Preparing Cloudflared config template"
  $templatePath = Join-Path $ScriptDir "cloudflared.yml.template"
  $targetPath = Join-Path $ScriptDir "cloudflared.yml"
  if (!(Test-Path $targetPath)) {
    Copy-Item $templatePath $targetPath
  }
}

function Register-StartupTask {
  param(
    [Parameter(Mandatory = $true)][string]$TaskName,
    [Parameter(Mandatory = $true)][string]$ScriptPath
  )

  $scriptAbs = (Resolve-Path $ScriptPath).Path
  $psExe = "$env:WINDIR\System32\WindowsPowerShell\v1.0\powershell.exe"
  $taskCmd = "`"$psExe`" -NoProfile -ExecutionPolicy Bypass -File `"$scriptAbs`""
  schtasks /Create /F /SC ONLOGON /RL HIGHEST /TN $TaskName /TR $taskCmd | Out-Null
}

function Create-StartupTasks {
  Write-Step "Creating startup tasks (ONLOGON)"
  Register-StartupTask -TaskName "CamMonitor-App" -ScriptPath (Join-Path $ScriptDir "run_cammonitor.ps1")
  Register-StartupTask -TaskName "CamMonitor-go2rtc" -ScriptPath (Join-Path $ScriptDir "run_go2rtc.ps1")
  Register-StartupTask -TaskName "CamMonitor-Caddy" -ScriptPath (Join-Path $ScriptDir "run_caddy.ps1")
  Register-StartupTask -TaskName "CamMonitor-Cloudflared" -ScriptPath (Join-Path $ScriptDir "run_cloudflared.ps1")
}

function Print-NextSteps {
  $bootstrapPath = Join-Path $ScriptDir "bootstrap-admin.txt"
  Write-Host ""
  Write-Host "Installation complete." -ForegroundColor Green
  Write-Host ""
  Write-Host "Default login credentials:"
  Write-Host "  Username: admin"
  if (Test-Path $bootstrapPath) {
    Write-Host "  Password file: $bootstrapPath" -ForegroundColor Yellow
    Write-Host "  (Open that file to see the generated password)" -ForegroundColor Yellow
  }
  Write-Host ""
  Write-Host "Next steps:"
  Write-Host "1. Edit $ScriptDir\cloudflared.yml and set your tunnel ID/credentials/hostname."
  Write-Host "2. Run Cloudflare login once:"
  Write-Host "   $BinDir\cloudflared.exe tunnel login"
  Write-Host "3. Start services manually (first test):"
  Write-Host "   powershell -ExecutionPolicy Bypass -File $ScriptDir\run_go2rtc.ps1"
  Write-Host "   powershell -ExecutionPolicy Bypass -File $ScriptDir\run_caddy.ps1"
  Write-Host "   powershell -ExecutionPolicy Bypass -File $ScriptDir\run_cammonitor.ps1"
  Write-Host "   powershell -ExecutionPolicy Bypass -File $ScriptDir\run_cloudflared.ps1"
  Write-Host ""
  Write-Host "Open: http://127.0.0.1:8080"
  Write-Host "Setup guide: deploy\windows\WINDOWS_LOCAL_SERVER_SETUP.md"
  if ($SkipStartupTasks) {
    Write-Host "Startup tasks were skipped by request." -ForegroundColor Yellow
    Write-Host "Rerun installer without -SkipStartupTasks to enable auto-start."
  } else {
    Write-Host "Startup tasks created successfully." -ForegroundColor Green
  }
}

Ensure-Python
Setup-Venv
Install-Go2rtc
Install-Caddy
Install-Cloudflared
Update-Config
Ensure-CloudflaredTemplate
if (-not $SkipStartupTasks) {
  Create-StartupTasks
}
Print-NextSteps
