#!/usr/bin/env bash
set -euo pipefail

INSTALL_DIR="${INSTALL_DIR:-/opt/cctv-monitor-kumarans}"
SERVICE_USER="${SERVICE_USER:-cammonitor}"
SERVICE_GROUP="${SERVICE_GROUP:-cammonitor}"
GO2RTC_VERSION="${GO2RTC_VERSION:-1.9.13}"
CADDY_VERSION="${CADDY_VERSION:-2.8.4}"
APP_PORT="${APP_PORT:-5001}"
PROXY_PORT="${PROXY_PORT:-8080}"
DATA_DIR="${DATA_DIR:-${INSTALL_DIR}/data}"
BOOTSTRAP_FILE="${BOOTSTRAP_FILE:-${INSTALL_DIR}/bootstrap-admin.txt}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"

log() {
  printf '\n[%s] %s\n' "$(date '+%H:%M:%S')" "$*"
}

fail() {
  printf '\nERROR: %s\n' "$*" >&2
  exit 1
}

require_root() {
  if [[ "${EUID}" -ne 0 ]]; then
    fail "Run this installer with sudo or as root."
  fi
}

detect_arch() {
  case "$(uname -m)" in
    x86_64|amd64) echo "amd64" ;;
    aarch64|arm64) echo "arm64" ;;
    *)
      fail "Unsupported architecture: $(uname -m). Supported: x86_64/amd64, aarch64/arm64."
      ;;
  esac
}

install_packages() {
  log "Installing required OS packages"
  apt-get update
  DEBIAN_FRONTEND=noninteractive apt-get install -y \
    python3 python3-venv python3-pip curl ca-certificates tar gzip \
    ffmpeg libopus0
  # libvpx and libx264 package names differ between Ubuntu 20.04 (libvpx6, libx264-155)
  # and 22.04+ (libvpx7, libx264-163). Install whichever is available; ffmpeg already
  # pulls the correct version as a dependency, so failures here are non-fatal.
  DEBIAN_FRONTEND=noninteractive apt-get install -y libvpx7 libx264-163 2>/dev/null \
    || DEBIAN_FRONTEND=noninteractive apt-get install -y libvpx6 libx264-155 2>/dev/null \
    || true
}

ensure_service_user() {
  if ! id -u "${SERVICE_USER}" >/dev/null 2>&1; then
    log "Creating service user ${SERVICE_USER}"
    useradd --system --home "${INSTALL_DIR}" --shell /usr/sbin/nologin "${SERVICE_USER}"
  fi
}

copy_app() {
  log "Copying application to ${INSTALL_DIR}"
  mkdir -p "${INSTALL_DIR}"
  tar \
    --exclude='.git' \
    --exclude='.venv' \
    --exclude='__pycache__' \
    --exclude='*.pyc' \
    --exclude='cam_monitor.db*' \
    --exclude='central_dashboard.db*' \
    --exclude='monitor.log' \
    --exclude='dashboard_script.js' \
    --exclude='tools' \
    -C "${REPO_ROOT}" -cf - . | tar -C "${INSTALL_DIR}" -xf -
  chown -R "${SERVICE_USER}:${SERVICE_GROUP}" "${INSTALL_DIR}"
}

setup_python() {
  log "Creating Python virtual environment"
  python3 -m venv "${INSTALL_DIR}/.venv"
  "${INSTALL_DIR}/.venv/bin/pip" install --upgrade pip
  "${INSTALL_DIR}/.venv/bin/pip" install -r "${INSTALL_DIR}/requirements.txt"
}

set_config_defaults() {
  log "Applying production-friendly defaults"
  python3 - <<PY
import configparser, pathlib, secrets
cfg_path = pathlib.Path("${INSTALL_DIR}/config.ini")
data_dir = pathlib.Path("${DATA_DIR}")
bootstrap_path = pathlib.Path("${BOOTSTRAP_FILE}")
cfg = configparser.ConfigParser()
cfg.read(cfg_path)
if not cfg.has_section("web"):
    cfg.add_section("web")
secret = cfg.get("web", "secret_key", fallback="change-this-to-a-random-secret-key")
if secret == "change-this-to-a-random-secret-key":
    secret = secrets.token_hex(32)
    cfg.set("web", "secret_key", secret)
cfg.set("web", "host", "127.0.0.1")
cfg.set("web", "port", "${APP_PORT}")
cfg.set("web", "dashboard_admin_name", cfg.get("web", "dashboard_admin_name", fallback="Administrator"))
default_user = cfg.get("web", "dashboard_username", fallback="admin").strip() or "admin"
default_pass = cfg.get("web", "dashboard_password", fallback="admin123")
generated_password = ""
if default_user.lower() == "admin" and default_pass == "admin123":
    generated_password = secrets.token_urlsafe(12)
    cfg.set("web", "dashboard_username", "admin")
    cfg.set("web", "dashboard_password", generated_password)
if not cfg.has_section("database"):
    cfg.add_section("database")
data_dir.mkdir(parents=True, exist_ok=True)
cfg.set("database", "db_path", str(data_dir / "cam_monitor.db"))
if not cfg.has_section("go2rtc"):
    cfg.add_section("go2rtc")
cfg.set("go2rtc", "enabled", "true")
cfg.set("go2rtc", "base_url", "http://127.0.0.1:1984")
cfg.set("go2rtc", "proxy_path", "/go2rtc")
if not cfg.has_section("setup"):
    cfg.add_section("setup")
if cfg.get("setup", "completed", fallback="false").lower() != "true":
    cfg.set("setup", "completed", "false")
with cfg_path.open("w") as f:
    cfg.write(f)
bootstrap_lines = [
    "CamMonitor bootstrap credentials",
    f"Username: {cfg.get('web', 'dashboard_username')}",
]
if generated_password:
    bootstrap_lines.append(f"Password: {generated_password}")
    bootstrap_lines.append("Status: Generated by installer because the default password was still in place.")
else:
    bootstrap_lines.append("Password: unchanged from existing config")
    bootstrap_lines.append("Status: Existing admin password preserved.")
bootstrap_path.write_text("\\n".join(bootstrap_lines) + "\\n", encoding="utf-8")
PY
  chown "${SERVICE_USER}:${SERVICE_GROUP}" "${INSTALL_DIR}/config.ini"
  chown -R "${SERVICE_USER}:${SERVICE_GROUP}" "${DATA_DIR}"
  chown root:${SERVICE_GROUP} "${BOOTSTRAP_FILE}"
  chmod 640 "${BOOTSTRAP_FILE}"
}

install_go2rtc() {
  local arch
  arch="$(detect_arch)"
  log "Installing go2rtc ${GO2RTC_VERSION} (${arch})"
  curl -L -o /usr/local/bin/go2rtc \
    "https://github.com/AlexxIT/go2rtc/releases/download/v${GO2RTC_VERSION}/go2rtc_linux_${arch}"
  chmod +x /usr/local/bin/go2rtc
}

install_caddy() {
  local arch tmpdir asset
  arch="$(detect_arch)"
  tmpdir="$(mktemp -d)"
  asset="caddy_${CADDY_VERSION}_linux_${arch}.tar.gz"
  log "Installing Caddy ${CADDY_VERSION} (${arch})"
  curl -L -o "${tmpdir}/${asset}" \
    "https://github.com/caddyserver/caddy/releases/download/v${CADDY_VERSION}/${asset}"
  tar -xzf "${tmpdir}/${asset}" -C "${tmpdir}"
  install -m 0755 "${tmpdir}/caddy" /usr/local/bin/caddy
  rm -rf "${tmpdir}"
}

install_configs() {
  log "Installing service and proxy configuration"
  mkdir -p /etc/caddy

  sed \
    -e "s|/opt/cam-monitor-v2|${INSTALL_DIR}|g" \
    -e "s|User=cammonitor|User=${SERVICE_USER}|g" \
    -e "s|Group=cammonitor|Group=${SERVICE_GROUP}|g" \
    "${INSTALL_DIR}/deploy/linux/cammonitor.service" > /etc/systemd/system/cammonitor.service

  sed \
    -e "s|/opt/cam-monitor-v2|${INSTALL_DIR}|g" \
    -e "s|User=cammonitor|User=${SERVICE_USER}|g" \
    -e "s|Group=cammonitor|Group=${SERVICE_GROUP}|g" \
    "${INSTALL_DIR}/deploy/linux/go2rtc.service" > /etc/systemd/system/go2rtc.service

  sed \
    -e "s|User=cammonitor|User=${SERVICE_USER}|g" \
    -e "s|Group=cammonitor|Group=${SERVICE_GROUP}|g" \
    "${INSTALL_DIR}/deploy/linux/caddy.service" > /etc/systemd/system/caddy.service

  sed \
    -e "s|:8080|:${PROXY_PORT}|g" \
    -e "s|127.0.0.1:5001|127.0.0.1:${APP_PORT}|g" \
    "${INSTALL_DIR}/deploy/linux/Caddyfile" > /etc/caddy/Caddyfile

  chown -R "${SERVICE_USER}:${SERVICE_GROUP}" /etc/caddy "${INSTALL_DIR}"
}

enable_services() {
  log "Enabling services"
  systemctl daemon-reload
  systemctl enable --now go2rtc
  systemctl enable --now cammonitor
  systemctl enable --now caddy
}

show_next_steps() {
  local host_ip
  host_ip="$(hostname -I 2>/dev/null | awk '{print $1}')"
  cat <<EOF

CamMonitor installation is complete.

Local URLs:
  CamMonitor app:  http://127.0.0.1:${APP_PORT}
  Caddy proxy:     http://127.0.0.1:${PROXY_PORT}
  Same-LAN access: http://${host_ip:-<server-ip>}:${PROXY_PORT}

Default login:
  Username: admin
  Password: $(grep -i password "${BOOTSTRAP_FILE}" | head -1 | cut -d' ' -f2-)
  (Full credentials saved to: ${BOOTSTRAP_FILE})

Next steps in the browser:
  1. Open http://${host_ip:-<server-ip>}:${PROXY_PORT}
  2. Log in
  3. Use the password stored in ${BOOTSTRAP_FILE}
  4. Update Site Details
  5. Upload the camera import template
  6. Verify live camera monitoring and NVR reachability

Service checks:
  sudo systemctl status cammonitor
  sudo systemctl status go2rtc
  sudo systemctl status caddy

If you want public remote access later:
  set up Cloudflare Tunnel to point the site hostname to http://127.0.0.1:${PROXY_PORT}
EOF
}

main() {
  if ! command -v apt-get >/dev/null 2>&1; then
    fail "This installer requires a Debian/Ubuntu system (apt-get not found)."
  fi
  require_root
  install_packages
  ensure_service_user
  copy_app
  setup_python
  set_config_defaults
  install_go2rtc
  install_caddy
  install_configs
  enable_services
  show_next_steps
}

main "$@"
